parameters:

    # Managers _________________

    fifteen_puzzle.user_manager.entity: FifteenPuzzleMainBundle:User
    fifteen_puzzle.user_manager.class: FifteenPuzzle\MainBundle\Manager\UserManager

services:

    # Managers _________________

    fifteen_puzzle.user_manager:
        class:        %fifteen_puzzle.user_manager.class%
        arguments:    [@doctrine.orm.entity_manager, %fifteen_puzzle.user_manager.entity%]
